# Generated by Django 3.2.5 on 2021-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='None', max_length=25)),
                ('importance_level', models.CharField(default='None', max_length=25)),
                ('short_description', models.TextField(default='None')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
