# Generated by Django 3.2.5 on 2021-07-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentActivity',
            new_name='CurrentActivitie',
        ),
    ]
