# Generated by Django 3.2.5 on 2021-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_currentactivity_currentactivitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentactivitie',
            name='importance_level',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Important', 'Important'), ('Very important', 'Very important'), ('Critical', 'Critical')], default='None', max_length=25),
        ),
    ]
