# Generated by Django 3.2.5 on 2021-07-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('activities', '0003_alter_currentactivitie_importance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivitie',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.personalproject'),
        ),
    ]
