# Generated by Django 3.2.5 on 2021-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('gmail', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
