# Generated by Django 3.2.5 on 2021-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_organization_githuborganization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githuborganization',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='githuborganization',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
