# Generated by Django 3.2.5 on 2021-07-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20210707_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuborganization',
            name='picture',
            field=models.ImageField(default='/organizations/default.jpg', upload_to='organizations/'),
        ),
    ]
