# Generated by Django 3.2.5 on 2021-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_businessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='posture',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
