# Generated by Django 3.2.5 on 2021-07-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('source_platform', models.CharField(default=None, max_length=50)),
                ('stack', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.developmentstack')),
            ],
        ),
    ]
